/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IntegrationLogsRouteImport } from './routes/integration-logs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PortMovedRouteImport } from './routes/port-moved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemMessagesRouteImport } from './routes/system-messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationLogsRoute = IntegrationLogsRouteImport.update({
  id: '/integration-logs',
  path: '/integration-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortMovedRoute = PortMovedRouteImport.update({
  id: '/port-moved',
  path: '/port-moved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMessagesRoute = SystemMessagesRouteImport.update({
  id: '/system-messages',
  path: '/system-messages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/integration-logs': typeof IntegrationLogsRoute
  '/integrations': typeof IntegrationsRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/port-moved': typeof PortMovedRoute
  '/settings': typeof SettingsRoute
  '/system-messages': typeof SystemMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/integration-logs': typeof IntegrationLogsRoute
  '/integrations': typeof IntegrationsRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/port-moved': typeof PortMovedRoute
  '/settings': typeof SettingsRoute
  '/system-messages': typeof SystemMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/integration-logs': typeof IntegrationLogsRoute
  '/integrations': typeof IntegrationsRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/port-moved': typeof PortMovedRoute
  '/settings': typeof SettingsRoute
  '/system-messages': typeof SystemMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/catalog'
    | '/dashboard'
    | '/diagnostics'
    | '/integration-logs'
    | '/integrations'
    | '/logs'
    | '/notifications'
    | '/port-moved'
    | '/settings'
    | '/system-messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/catalog'
    | '/dashboard'
    | '/diagnostics'
    | '/integration-logs'
    | '/integrations'
    | '/logs'
    | '/notifications'
    | '/port-moved'
    | '/settings'
    | '/system-messages'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/catalog'
    | '/dashboard'
    | '/diagnostics'
    | '/integration-logs'
    | '/integrations'
    | '/logs'
    | '/notifications'
    | '/port-moved'
    | '/settings'
    | '/system-messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  IntegrationLogsRoute: typeof IntegrationLogsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LogsRoute: typeof LogsRoute
  NotificationsRoute: typeof NotificationsRoute
  PortMovedRoute: typeof PortMovedRoute
  SettingsRoute: typeof SettingsRoute
  SystemMessagesRoute: typeof SystemMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-logs': {
      id: '/integration-logs'
      path: '/integration-logs'
      fullPath: '/integration-logs'
      preLoaderRoute: typeof IntegrationLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-moved': {
      id: '/port-moved'
      path: '/port-moved'
      fullPath: '/port-moved'
      preLoaderRoute: typeof PortMovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-messages': {
      id: '/system-messages'
      path: '/system-messages'
      fullPath: '/system-messages'
      preLoaderRoute: typeof SystemMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  IntegrationLogsRoute: IntegrationLogsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LogsRoute: LogsRoute,
  NotificationsRoute: NotificationsRoute,
  PortMovedRoute: PortMovedRoute,
  SettingsRoute: SettingsRoute,
  SystemMessagesRoute: SystemMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
