import { useQuery } from '@tanstack/react-query'
import { ArrowUpRight, BadgeCheck, ChevronDown, CloudDownload, Download, ExternalLink, Heart, ListFilter, Puzzle, RefreshCw, Settings2, Star, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { api } from '../lib/api'
import type { Integration } from '../lib/models'
import { Modal } from './Modal'
import { IntegrationSetupModal } from './IntegrationSetupModal'

function stateLabel(item: Integration) { if (item.management === 'official') return 'Firmware managed'; if (item.management === 'external') return 'External'; if (item.updateAvailable) return `Update ${item.latestVersion ?? 'available'}`; if (item.connectionState === 'not_configured') return 'Needs setup'; if (item.connectionState === 'connected' || item.connectionState === 'ok') return 'Connected'; if (item.connectionState === 'error' || item.connectionState === 'disconnected') return 'Disconnected'; return item.installState === 'available' ? 'Available' : 'Installed' }
function stateTone(item: Integration) { if (item.updateAvailable || item.connectionState === 'not_configured') return 'warning'; if (item.connectionState === 'error' || item.connectionState === 'disconnected') return 'danger'; if (item.connectionState === 'connected' || item.connectionState === 'ok') return 'success'; return 'neutral' }
function githubRepository(homepage: string | null) { const match = homepage?.match(/github\.com\/([^/]+)\/([^/#?]+)/i); return match ? { owner: match[1], repo: match[2].replace(/\.git$/, '') } : null }
function supportLabel(platform: string) { return ({ github: 'GitHub Sponsors', buy_me_a_coffee: 'Buy Me a Coffee', paypal: 'PayPal', patreon: 'Patreon', ko_fi: 'Ko-fi', 'ko-fi': 'Ko-fi', venmo: 'Venmo', cashapp: 'Cash App' } as Record<string, string>)[platform] ?? 'Support' }

export function IntegrationCard({ item, onInstall, onUpdate, onSelfUpdate, onBackup, onDelete, operation, pending = false }: { item: Integration; onInstall?: (item: Integration, version?: string) => void; onUpdate?: (item: Integration, version?: string) => void; onSelfUpdate?: (item: Integration, version?: string) => void; onBackup?: (item: Integration) => void; onDelete?: (item: Integration) => void; operation?: 'install' | 'update' | 'backup' | 'delete'; pending?: boolean }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [supportOpen, setSupportOpen] = useState(false)
  const [versionModal, setVersionModal] = useState(false)
  const [deleteModal, setDeleteModal] = useState(false)
  const [setupModal, setSetupModal] = useState(false)
  const [manualVersion, setManualVersion] = useState('')
  const menuRef = useRef<HTMLDivElement>(null)
  const supportRef = useRef<HTMLDivElement>(null)
  const repository = useMemo(() => githubRepository(item.homepage), [item.homepage])
  const isSelfUpdate = item.capabilities.selfUpdate
  const compactVersions = useQuery({ queryKey: ['versions', item.id, 'recent', isSelfUpdate], queryFn: () => api.integrationVersions(repository!.owner, repository!.repo, item.id, false, isSelfUpdate), enabled: menuOpen && Boolean(repository), staleTime: 60_000 })
  const allVersions = useQuery({ queryKey: ['versions', item.id, 'all', isSelfUpdate], queryFn: () => api.integrationVersions(repository!.owner, repository!.repo, item.id, true, isSelfUpdate), enabled: versionModal && Boolean(repository), staleTime: 60_000 })
  const primaryAction = item.capabilities.install ? 'Install' : item.capabilities.update || isSelfUpdate ? 'Update' : null
  const canCreateBackup = item.installed && item.capabilities.backup && item.connectionState !== 'not_configured'
  const isReconfigure = item.connectionState !== 'not_configured' && (item.installState === 'configured' || Boolean(item.instanceId))
  const act = (version?: string) => primaryAction === 'Install' ? onInstall?.(item, version) : isSelfUpdate ? onSelfUpdate?.(item, version) : onUpdate?.(item, version)
  const selectVersion = (version: string) => { setMenuOpen(false); setVersionModal(false); act(version) }
  useEffect(() => {
    const dismiss = (event: PointerEvent) => { const target = event.target as Node; if (menuRef.current && !menuRef.current.contains(target)) setMenuOpen(false); if (supportRef.current && !supportRef.current.contains(target)) setSupportOpen(false) }
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMenuOpen(false); setSupportOpen(false) } }
    document.addEventListener('pointerdown', dismiss); document.addEventListener('keydown', escape)
    return () => { document.removeEventListener('pointerdown', dismiss); document.removeEventListener('keydown', escape) }
  }, [])
  return <article className={`integration-card catalog-card ${item.driverInstalled ? 'is-installed' : 'is-available'} ${operation ? 'operation-pending' : ''}`} aria-busy={Boolean(operation)}>
    <div className="card-heading"><div className={`integration-mark ${stateTone(item)}`}><Puzzle aria-hidden="true" /></div><div className="card-title"><h2>{item.name}</h2><div className="metadata">{item.version && <span>v{item.version}</span>}{item.developer && (item.developerHomepage ? <a href={item.developerHomepage} target="_blank" rel="noreferrer">{item.developer}</a> : <span>{item.developer}</span>)}{item.repository.stars > 0 && <span className="repo-stat"><Star />{item.repository.stars}</span>}</div></div><span className={`state-pill ${stateTone(item)}`}>{stateLabel(item)}</span></div>
    <p className="card-description">{item.description || 'No description is available for this integration.'}</p>
    <div className="capability-row catalog-signals">{item.categories.slice(0, 2).map(category => <span className="catalog-category" key={category}>{category}</span>)}{item.capabilities.backup && <span title="Configuration backups are supported at this installed version"><CloudDownload aria-hidden="true" /> Backups supported</span>}{item.management === 'custom' && <span><BadgeCheck aria-hidden="true" /> Custom</span>}</div>
    <footer className="card-actions catalog-card-footer"><div className="action-row catalog-actions">
      {item.supportLinks.length > 0 && <div className="card-menu support-menu" ref={supportRef}><button className="icon-action donate-action" type="button" title={`Support ${item.developer ?? item.name}`} data-tooltip="Support developer" onClick={() => setSupportOpen(open => !open)} aria-label={`Support ${item.developer ?? item.name}`} aria-expanded={supportOpen}><Heart /></button>{supportOpen && <div className="card-popover support-popover"><strong>Support {item.developer ?? item.name}</strong>{item.supportLinks.map(link => <a key={link.url} href={link.url} target="_blank" rel="noreferrer">{supportLabel(link.platform)}<ExternalLink /></a>)}</div>}</div>}
      {item.homepage && <a className="icon-action" href={item.homepage} target="_blank" rel="noreferrer" title={`Open ${item.name} homepage`} data-tooltip="Open homepage" aria-label={`Open ${item.name} homepage`}><ExternalLink /></a>}
      {item.capabilities.configure && <button className="compact-action solo setup-action" type="button" title={`${isReconfigure ? 'Reconfigure' : 'Configure'} ${item.name}`} disabled={pending} onClick={() => setSetupModal(true)}><Settings2 />{isReconfigure ? 'Reconfigure' : 'Configure'}</button>}
      {canCreateBackup && <button className="icon-action" type="button" title={`Back up ${item.name}`} data-tooltip="Create backup" disabled={pending} onClick={() => onBackup?.(item)} aria-label={`Back up ${item.name}`}><CloudDownload /></button>}
      {item.capabilities.deleteDriver && <button className="icon-action" type="button" title={`Delete ${item.name}`} data-tooltip="Delete integration" disabled={pending} onClick={() => setDeleteModal(true)} aria-label={`Delete ${item.name}`}><Trash2 /></button>}
      {primaryAction && <div className="card-menu action-split" ref={menuRef}><button className={`compact-action ${primaryAction === 'Update' ? 'update' : ''}`} type="button" title={`${primaryAction} latest version of ${item.name}`} disabled={pending} onClick={() => act()}>{primaryAction === 'Update' ? <RefreshCw /> : <Download />}{primaryAction === 'Update' ? item.latestVersion ?? 'Update' : 'Install'}</button>{repository && <button className={`compact-action split-toggle ${primaryAction === 'Update' ? 'update' : ''}`} type="button" title={`Choose a version of ${item.name}`} aria-label={`Choose a version of ${item.name}`} aria-expanded={menuOpen} onClick={() => setMenuOpen(open => !open)}><ChevronDown /></button>}{menuOpen && <div className="card-popover version-popover"><strong><ListFilter /> Recent versions</strong>{compactVersions.isLoading && <span className="menu-loading"><RefreshCw className="spin" />Loading releases…</span>}{compactVersions.isError && <span className="menu-error">Could not load versions.</span>}{compactVersions.data?.releases.map(release => <button key={release.tag_name} type="button" disabled={pending} title={`Install ${release.tag_name}`} onClick={() => selectVersion(release.tag_name)}><span>{release.tag_name}{release.is_beta && <em>Beta</em>}</span><small>{release.name || release.published_at}</small></button>)}<button className="menu-footer-action" type="button" onClick={() => { setMenuOpen(false); setVersionModal(true) }}>All versions &amp; manual entry <ArrowUpRight /></button></div>}</div>}
    </div></footer>
    {versionModal && repository && <Modal title={`Choose a version — ${item.name}`} close={() => setVersionModal(false)}><div className="version-dialog"><p>Install a compatible release, or enter an exact GitHub version tag.</p>{allVersions.data?.versionFloor && <div className="version-warning">Versions at or below <strong>{allVersions.data.versionFloor}</strong> require migration and cannot be installed automatically.</div>}<h3>Available releases</h3>{allVersions.isLoading ? <div className="menu-loading"><RefreshCw className="spin" />Loading releases…</div> : allVersions.isError ? <div className="notice error">Could not load available versions.</div> : <div className="release-list">{allVersions.data?.releases.map(release => <button key={release.tag_name} type="button" disabled={pending} onClick={() => selectVersion(release.tag_name)}><span><strong>{release.tag_name}</strong>{release.is_beta && <em>Beta</em>}<small>{release.name || release.published_at}</small></span><Download /></button>)}</div>}<h3>Specify version</h3><form className="manual-version" onSubmit={event => { event.preventDefault(); if (manualVersion.trim()) selectVersion(manualVersion.trim()) }}><input value={manualVersion} onChange={event => setManualVersion(event.target.value)} placeholder="e.g. v1.2.3" pattern="^v?[0-9]+\.[0-9]+\.[0-9]+.*$" title="Enter a version such as v1.2.3" required /><button className="primary-action" disabled={pending}><Download /> {primaryAction}</button></form><small>Enter an exact GitHub version tag, with or without the “v” prefix.</small></div></Modal>}
    {setupModal && <IntegrationSetupModal item={item} close={() => setSetupModal(false)} />}
    {deleteModal && <Modal title={`Delete ${item.name}?`} close={() => setDeleteModal(false)}><div className="confirm-dialog"><p>This removes the integration and its configuration from the Remote. This cannot be undone.</p><div><button className="secondary-action" type="button" onClick={() => setDeleteModal(false)}>Cancel</button><button className="danger-action" type="button" onClick={() => { setDeleteModal(false); onDelete?.(item) }}><Trash2 /> Delete integration</button></div></div></Modal>}
    {operation && <div className="card-operation-overlay" role="status"><RefreshCw className="spin" aria-hidden="true" /><div><strong>{{ install: 'Installing integration', update: 'Updating integration', backup: 'Creating backup', delete: 'Deleting integration' }[operation]}</strong><span>{operation === 'backup' ? 'Saving the current configuration…' : operation === 'delete' ? 'Removing it from the Remote…' : 'Applying changes on the Remote…'}</span></div></div>}
  </article>
}
